// Code generated by hertz generator.

package main

import (
	"flag"
	"github.com/cloudwego/hertz/pkg/app/server"
	"sign-lottery/cmd/api/biz/router"
	"sign-lottery/pkg/constants"
	"sign-lottery/service/base"
	"sign-lottery/service/lottery"
	"sign-lottery/service/sign"
)

var ServerName string

func main() {
	flag.StringVar(&ServerName, "server", "api", "which server to start")
	switch ServerName {
	case constants.ApiServiceName:
		h := server.Default()
		router.GeneratedRegister(h)
		h.Spin()
		break
	case constants.BaseServiceName:
		base.BaseServer()
	case constants.SignServiceName:
		sign.SignServer()
	case constants.LotteryServiceName:
		lottery.LotteryServer()
	}
}
