// Code generated by hertz generator.

package main

import (
	"sign-lottery/cmd/api/biz/router"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	router.GeneratedRegister(h)
	h.Spin()
}
