version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: lottery-mysql
    volumes:
      - ./pkg/config/mysql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      - MYSQL_DATABASE=lottery
      - MYSQL_USER=yogen
      - MYSQL_PASSWORD=yogen123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    command:
      -  --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    container_name: lottery-redis
    ports:
      - "9911:6379"
  rabbitmq:
    image: rabbitmq:management
    container_name: lottery-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - TZ:Asia/Shanghai
      - RABBITMQ_DEFAULT_USER:yogen
      - RABBITMQ_DEFAULT_PASS:yogen123
      - RABBITMQ_DEFAULT_VHOST:lottery
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: lottery-etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - "9912:2379"
