// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
package model

import (
	"time"
	"gorm.io/plugin/soft_delete"
)

const TableNameActivity = "activity"

// Activity mapped from table <activity>
type Activity struct {
	ID        int                   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time            `gorm:"column:created_at;type:int unsigned;autoCreateTime" json:"created_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	Name      string                `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Des       *string               `gorm:"column:des;type:tinytext" json:"des"`
	Picture   *string               `gorm:"column:picture;type:varchar(30)" json:"picture"`
	Cost      *int32                  `gorm:"column:cost;type:int unsigned" json:"cost"`
	UID       *int64                `gorm:"column:uid;type:bigint unsigned" json:"uid"`
	Gid       int                   `gorm:"column:gid;type:int unsigned;not null" json:"gid"`
	Start     *time.Time            `gorm:"column:start;type:datetime" json:"start"`
	End       *time.Time            `gorm:"column:end;type:datetime" json:"end"`
	Num       *int64                `gorm:"column:num;type:bigint unsigned" json:"num"`
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
