// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"gorm.io/plugin/soft_delete"
)

const TableNameAskLeave = "ask_leave"

// AskLeave mapped from table <ask_leave>
type AskLeave struct {
	ID        int                   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID       int64                 `gorm:"column:uid;type:bigint unsigned;not null" json:"uid"`
	CreatedAt *time.Time            `gorm:"column:created_at;type:int unsigned;autoCreateTime" json:"created_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	Issue     string                `gorm:"column:issue;type:text;not null" json:"issue"`
	Time      *time.Time            `gorm:"column:time;type:datetime" json:"time"`
	Gid       int                   `gorm:"column:gid;type:int unsigned;not null" json:"gid"`
}

// TableName AskLeave's table name
func (*AskLeave) TableName() string {
	return TableNameAskLeave
}
