// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"gorm.io/plugin/soft_delete"
)

const TableNameSignGroupPos = "sign_group_pos"

// SignGroupPo mapped from table <sign_group_pos>
type SignGroupPos struct {
	ID         int                   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name       string                `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Gid        int                   `gorm:"column:gid;type:int unsigned;not null" json:"gid"`
	CreatedAt  *time.Time            `gorm:"column:created_at;type:int unsigned;autoCreateTime" json:"created_at"`
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UpdatedAt  *time.Time            `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	Longtitude float64               `gorm:"column:longtitude;type:double(9,6);not null" json:"longtitude"`
	Latitude   float64               `gorm:"column:latitude;type:double(9,6);not null" json:"latitude"`
}

// TableName SignGroupPo's table name
func (*SignGroupPos) TableName() string {
	return TableNameSignGroupPos
}
