// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"gorm.io/plugin/soft_delete"
)

const TableNameSignMonth = "sign_month"

// SignMonth mapped from table <sign_month>
type SignMonth struct {
	ID        int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time            `gorm:"column:created_at;type:int unsigned;autoCreateTime" json:"created_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	Month     string                `gorm:"column:month;type:char(7);not null" json:"month"`
	Gid       int32                   `gorm:"column:gid;type:int unsigned;not null" json:"gid"`
	BitSign   *int                  `gorm:"column:bit_sign;type:int" json:"bit_sign"`
	UID       int64                 `gorm:"column:uid;type:bigint unsigned;not null" json:"uid"`
}

// TableName SignMonth's table name
func (*SignMonth) TableName() string {
	return TableNameSignMonth
}
