// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"gorm.io/plugin/soft_delete"
)

const TableNameUserOrder = "user_order"

// UserOrder mapped from table <user_order>
type UserOrder struct {
	ID        int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time            `gorm:"column:created_at;type:int unsigned;autoCreateTime" json:"created_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UpdatedAt *time.Time            `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	UID       int64                 `gorm:"column:uid;type:bigint unsigned;not null" json:"uid"`
	Pid       int                   `gorm:"column:pid;type:int unsigned;not null" json:"pid"`
}

// TableName UserOrder's table name
func (*UserOrder) TableName() string {
	return TableNameUserOrder
}
