// Code generated by Kitex v0.5.1. DO NOT EDIT.

package signservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sign "sign-lottery/kitex_gen/sign"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Sign(ctx context.Context, req *sign.SignRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error)
	AskLeave(ctx context.Context, req *sign.AskLeaveRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error)
	GetMonthSign(ctx context.Context, req *sign.GetMonthSignRequest, callOptions ...callopt.Option) (r *sign.MonthSignResponse, err error)
	GetAllRecord(ctx context.Context, req *sign.GetAllRecordRequest, callOptions ...callopt.Option) (r *sign.RecordsResponse, err error)
	GetUserRecord(ctx context.Context, req *sign.GetUserRecordRequest, callOptions ...callopt.Option) (r *sign.RecordsResponse, err error)
	SignPosAdd(ctx context.Context, req *sign.SignPosAddRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error)
	SignPosDel(ctx context.Context, req *sign.SignPosDelRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error)
	GetSignPos(ctx context.Context, req *sign.GetSignPosRequest, callOptions ...callopt.Option) (r *sign.GetSignPosResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSignServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSignServiceClient struct {
	*kClient
}

func (p *kSignServiceClient) Sign(ctx context.Context, req *sign.SignRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sign(ctx, req)
}

func (p *kSignServiceClient) AskLeave(ctx context.Context, req *sign.AskLeaveRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AskLeave(ctx, req)
}

func (p *kSignServiceClient) GetMonthSign(ctx context.Context, req *sign.GetMonthSignRequest, callOptions ...callopt.Option) (r *sign.MonthSignResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMonthSign(ctx, req)
}

func (p *kSignServiceClient) GetAllRecord(ctx context.Context, req *sign.GetAllRecordRequest, callOptions ...callopt.Option) (r *sign.RecordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllRecord(ctx, req)
}

func (p *kSignServiceClient) GetUserRecord(ctx context.Context, req *sign.GetUserRecordRequest, callOptions ...callopt.Option) (r *sign.RecordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserRecord(ctx, req)
}

func (p *kSignServiceClient) SignPosAdd(ctx context.Context, req *sign.SignPosAddRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignPosAdd(ctx, req)
}

func (p *kSignServiceClient) SignPosDel(ctx context.Context, req *sign.SignPosDelRequest, callOptions ...callopt.Option) (r *sign.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignPosDel(ctx, req)
}

func (p *kSignServiceClient) GetSignPos(ctx context.Context, req *sign.GetSignPosRequest, callOptions ...callopt.Option) (r *sign.GetSignPosResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSignPos(ctx, req)
}
