// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __ctivity_ddMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __ctivitydelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_ctivitybygidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_ctivitybyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_ll_ctivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __ctivityupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __dminloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userdelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_lluserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _groupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _add0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _del0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _groupdelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgroupbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _joingroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llgroupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _groupupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prizeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _add1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prize_ddMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprizeby_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chooseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _choose0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _del1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prizedelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprizebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _update0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prizeupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmonthsignbygidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _add2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sign0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _leaveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __skleaveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _monthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmonthsignMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _posMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signpos_ddMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signposdelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsignposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_llrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuser_ddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avaterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuser_vaterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gid0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbygidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuserpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registe0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
